server:
  port: 8070

spring:
  application:
    name: TransactionTest
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-j6cy09zgwol1xifzk3o.mysql.rds.aliyuncs.com:3306/t_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: t_test
    password: aa123456
    druid:
      initial-size: 1
      #最小连接池数量
      min-idle: 1
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 60000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement
      pool-prepared-statements: true
      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  data:
    mongodb:
      uri: mongodb://t_test:aA21212312s@dds-j6c09d2bd18c8cb41198-pub.mongodb.rds.aliyuncs.com:3717,dds-j6c09d2bd18c8cb42374-pub.mongodb.rds.aliyuncs.com:3717/t_test?replicaSet=mgset-38121708

